### ISSUE TITLE
Please Provide ordered description to implement the code

### ISSUE THREAD

**Issue by chanchalIITP** [ThomasChen94/Authorship-Identification#9]

**Comment by chanchalIITP** [comment]
Please provide description of the model you have generated.  I am not getting how to use this repository for Author identification. I have read the attached report, but I am not getting how to implement it.

**Comment by ghost** [comment]
Hey thanks for posting your issue! This is a course project and we were pretty new to NLP with deep learning. What we did was to follow the format of how our course assignment is written and wrap the model training/testing with our own code. It's a bit crude but it worked. I would not exactly recommend looking at our code for the model description. However you can find our report for this project [here](https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1174/reports/2760185.pdf). Hope it's helpful for your project.

**Comment by chanchalIITP** [comment]
Thank you for replying. I know It was a course project, but it would be very helpful, if u will provide an ordered way of implementation. Since I am also new in this area and I have to do the same project. If I would be able to implement your code, then I would be able to develop a new one.  I just want an ordered description (e.g : For sentence level : first run Create_Sent_set.py --> Then -->  Like this). I would be greatful for this. Your help could lead me in a better direction. I have already studied your report, but due to weak coding background I am not able to exactly know how to implement it. 

Thank you
Hoping for your kind reply.

**Comment by chanchalIITP** [comment]
<https://github.com/ThomasChen94/Authorship-Identification/issues/9#issuecomment-424576036>

Thank you for replying. I know It was a course project, but it would be
very helpful, if u will provide an ordered way of implementation. Since I
am also new in this area and I have to do the same project. If I would be
able to implement your code, then I would be able to develop a new one. I
just want an ordered description (e.g : For sentence level : first run
Create_Sent_set.py --> Then --> Like this). I would be greatful for this.
Your help could lead me in a better direction. I have already studied your
report, but due to weak coding background I am not able to exactly know how
to implement it.
Best Regards,
Chanchal Suman
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

PhD Scholar, Dept. of CSE,
Indian Institute of Technology, Patna,
Work-email: 1821cs11@iitp.ac.in <1821cs05@iitp.ac.in>
Alternate-email: chanchaliitp@gmail.com <ghosh.soumitra2@gmail.com>

**Comment by ghost** [comment]
To be honest, our model isn't complicated at all if you know how RNN models work. I would suggest improving your understanding of NLP with deep learning first so you can learn things in a step-by-step fashion. Our [course website](http://web.stanford.edu/class/cs224n/) has a lot of helpful information and you can always look up tutorials online for NLP with deep learning. Please abide the GitHub courtesy of not replying in closed issue.

**Comment by chanchalIITP** [comment]
Thank you sir,
I Will try to learn deep learning and will try to implement the code
myself. Thanks a lot for replying.
I am very new to GitHub, so unaware about the closed issue rule.

Thanks and Best Regards,
Chanchal Suman
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

PhD Scholar, Dept. of CSE,
Indian Institute of Technology, Patna,
Work-email: 1821cs11@iitp.ac.in <1821cs05@iitp.ac.in>
Alternate-email: chanchaliitp@gmail.com <ghosh.soumitra2@gmail.com>
